######  Detection Model  ######

model-onnx: /home/jetson/catkin_ws/src/SimpleNetwork/src/models/best.onnx        # Path to the ONNX model.
model-engine: /home/jetson/catkin_ws/src/SimpleNetwork/src/models/best.engine  # Path to the ONNX model.
class-names: [ 'apple' ]            # Class names of detected objects
conf-threshold: 0.85                 # Confidence threshold for filtering detections.
iou-threshold: 0.85                 # IoU (Intersection over Union) threshold for non-maximum suppression.


######  RealSense Config  ######
image-width: 640                   # The width of the image captured by the RealSense.
image-height: 480                   # The height of the image captured by the RealSense.
realsense-fps: 30                   # The frame rate of the image captured by the RealSense.
