// Generated by gencpp from file stereo_vision/ObjectDetection.msg
// DO NOT EDIT!


#ifndef STEREO_VISION_MESSAGE_OBJECTDETECTION_H
#define STEREO_VISION_MESSAGE_OBJECTDETECTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace stereo_vision
{
template <class ContainerAllocator>
struct ObjectDetection_
{
  typedef ObjectDetection_<ContainerAllocator> Type;

  ObjectDetection_()
    : header()
    , class_name()
    , confidence(0.0)
    , x_min(0.0)
    , y_min(0.0)
    , x_max(0.0)
    , y_max(0.0)
    , x_3d(0.0)
    , y_3d(0.0)
    , z_3d(0.0)
    , distance(0.0)  {
    }
  ObjectDetection_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , class_name(_alloc)
    , confidence(0.0)
    , x_min(0.0)
    , y_min(0.0)
    , x_max(0.0)
    , y_max(0.0)
    , x_3d(0.0)
    , y_3d(0.0)
    , z_3d(0.0)
    , distance(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _class_name_type;
  _class_name_type class_name;

   typedef float _confidence_type;
  _confidence_type confidence;

   typedef float _x_min_type;
  _x_min_type x_min;

   typedef float _y_min_type;
  _y_min_type y_min;

   typedef float _x_max_type;
  _x_max_type x_max;

   typedef float _y_max_type;
  _y_max_type y_max;

   typedef float _x_3d_type;
  _x_3d_type x_3d;

   typedef float _y_3d_type;
  _y_3d_type y_3d;

   typedef float _z_3d_type;
  _z_3d_type z_3d;

   typedef float _distance_type;
  _distance_type distance;





  typedef boost::shared_ptr< ::stereo_vision::ObjectDetection_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::stereo_vision::ObjectDetection_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectDetection_

typedef ::stereo_vision::ObjectDetection_<std::allocator<void> > ObjectDetection;

typedef boost::shared_ptr< ::stereo_vision::ObjectDetection > ObjectDetectionPtr;
typedef boost::shared_ptr< ::stereo_vision::ObjectDetection const> ObjectDetectionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::stereo_vision::ObjectDetection_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::stereo_vision::ObjectDetection_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::stereo_vision::ObjectDetection_<ContainerAllocator1> & lhs, const ::stereo_vision::ObjectDetection_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.class_name == rhs.class_name &&
    lhs.confidence == rhs.confidence &&
    lhs.x_min == rhs.x_min &&
    lhs.y_min == rhs.y_min &&
    lhs.x_max == rhs.x_max &&
    lhs.y_max == rhs.y_max &&
    lhs.x_3d == rhs.x_3d &&
    lhs.y_3d == rhs.y_3d &&
    lhs.z_3d == rhs.z_3d &&
    lhs.distance == rhs.distance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::stereo_vision::ObjectDetection_<ContainerAllocator1> & lhs, const ::stereo_vision::ObjectDetection_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace stereo_vision

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::stereo_vision::ObjectDetection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::stereo_vision::ObjectDetection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stereo_vision::ObjectDetection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stereo_vision::ObjectDetection_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stereo_vision::ObjectDetection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stereo_vision::ObjectDetection_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::stereo_vision::ObjectDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "406e440572e8e594fa2c1d30451e5901";
  }

  static const char* value(const ::stereo_vision::ObjectDetection_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x406e440572e8e594ULL;
  static const uint64_t static_value2 = 0xfa2c1d30451e5901ULL;
};

template<class ContainerAllocator>
struct DataType< ::stereo_vision::ObjectDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "stereo_vision/ObjectDetection";
  }

  static const char* value(const ::stereo_vision::ObjectDetection_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::stereo_vision::ObjectDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"string class_name\n"
"float32 confidence\n"
"float32 x_min\n"
"float32 y_min\n"
"float32 x_max\n"
"float32 y_max\n"
"float32 x_3d       # X position in 3D space (cm)\n"
"float32 y_3d       # Y position in 3D space (cm)\n"
"float32 z_3d       # Z position in 3D space (cm)\n"
"float32 distance   # Distance to object (cm) \n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::stereo_vision::ObjectDetection_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::stereo_vision::ObjectDetection_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.class_name);
      stream.next(m.confidence);
      stream.next(m.x_min);
      stream.next(m.y_min);
      stream.next(m.x_max);
      stream.next(m.y_max);
      stream.next(m.x_3d);
      stream.next(m.y_3d);
      stream.next(m.z_3d);
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectDetection_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::stereo_vision::ObjectDetection_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::stereo_vision::ObjectDetection_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "class_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.class_name);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "confidence: ";
    Printer<float>::stream(s, indent + "  ", v.confidence);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "x_min: ";
    Printer<float>::stream(s, indent + "  ", v.x_min);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y_min: ";
    Printer<float>::stream(s, indent + "  ", v.y_min);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "x_max: ";
    Printer<float>::stream(s, indent + "  ", v.x_max);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y_max: ";
    Printer<float>::stream(s, indent + "  ", v.y_max);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "x_3d: ";
    Printer<float>::stream(s, indent + "  ", v.x_3d);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y_3d: ";
    Printer<float>::stream(s, indent + "  ", v.y_3d);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "z_3d: ";
    Printer<float>::stream(s, indent + "  ", v.z_3d);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STEREO_VISION_MESSAGE_OBJECTDETECTION_H
