set(_CATKIN_CURRENT_PACKAGE "liancheng_socket")
set(liancheng_socket_VERSION "0.0.0")
set(liancheng_socket_MAINTAINER "msi <msi@todo.todo>")
set(liancheng_socket_PACKAGE_FORMAT "2")
set(liancheng_socket_BUILD_DEPENDS "message_generation" "roscpp" "rospy" "std_msgs" "moveit_msgs" "tf2" "tf2_ros" "sensor_msgs" "geometry_msgs")
set(liancheng_socket_BUILD_EXPORT_DEPENDS "message_generation" "roscpp" "rospy" "std_msgs" "tf2" "tf2_ros")
set(liancheng_socket_BUILDTOOL_DEPENDS "catkin")
set(liancheng_socket_BUILDTOOL_EXPORT_DEPENDS )
set(liancheng_socket_EXEC_DEPENDS "message_runtime" "roscpp" "rospy" "std_msgs" "moveit_msgs" "tf2" "tf2_ros")
set(liancheng_socket_RUN_DEPENDS "message_runtime" "roscpp" "rospy" "std_msgs" "moveit_msgs" "tf2" "tf2_ros" "message_generation")
set(liancheng_socket_TEST_DEPENDS )
set(liancheng_socket_DOC_DEPENDS )
set(liancheng_socket_URL_WEBSITE "")
set(liancheng_socket_URL_BUGTRACKER "")
set(liancheng_socket_URL_REPOSITORY "")
set(liancheng_socket_DEPRECATED "")