// Generated by gencpp from file liancheng_socket/ReadOutput.msg
// DO NOT EDIT!


#ifndef LIANCHENG_SOCKET_MESSAGE_READOUTPUT_H
#define LIANCHENG_SOCKET_MESSAGE_READOUTPUT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace liancheng_socket
{
template <class ContainerAllocator>
struct ReadOutput_
{
  typedef ReadOutput_<ContainerAllocator> Type;

  ReadOutput_()
    : header()
    , data_form(0)
    , data(0)  {
    }
  ReadOutput_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , data_form(0)
    , data(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _data_form_type;
  _data_form_type data_form;

   typedef uint16_t _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::liancheng_socket::ReadOutput_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::liancheng_socket::ReadOutput_<ContainerAllocator> const> ConstPtr;

}; // struct ReadOutput_

typedef ::liancheng_socket::ReadOutput_<std::allocator<void> > ReadOutput;

typedef boost::shared_ptr< ::liancheng_socket::ReadOutput > ReadOutputPtr;
typedef boost::shared_ptr< ::liancheng_socket::ReadOutput const> ReadOutputConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::liancheng_socket::ReadOutput_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::liancheng_socket::ReadOutput_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::liancheng_socket::ReadOutput_<ContainerAllocator1> & lhs, const ::liancheng_socket::ReadOutput_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.data_form == rhs.data_form &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::liancheng_socket::ReadOutput_<ContainerAllocator1> & lhs, const ::liancheng_socket::ReadOutput_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace liancheng_socket

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::liancheng_socket::ReadOutput_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::liancheng_socket::ReadOutput_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::liancheng_socket::ReadOutput_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::liancheng_socket::ReadOutput_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::liancheng_socket::ReadOutput_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::liancheng_socket::ReadOutput_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::liancheng_socket::ReadOutput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a62420f87b5442275e7e63314bd0b030";
  }

  static const char* value(const ::liancheng_socket::ReadOutput_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa62420f87b544227ULL;
  static const uint64_t static_value2 = 0x5e7e63314bd0b030ULL;
};

template<class ContainerAllocator>
struct DataType< ::liancheng_socket::ReadOutput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "liancheng_socket/ReadOutput";
  }

  static const char* value(const ::liancheng_socket::ReadOutput_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::liancheng_socket::ReadOutput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"uint8 data_form\n"
"uint16  data\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::liancheng_socket::ReadOutput_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::liancheng_socket::ReadOutput_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.data_form);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReadOutput_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::liancheng_socket::ReadOutput_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::liancheng_socket::ReadOutput_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "data_form: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.data_form);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "data: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIANCHENG_SOCKET_MESSAGE_READOUTPUT_H
