// Generated by gencpp from file liancheng_socket/SwitchOrder.msg
// DO NOT EDIT!


#ifndef LIANCHENG_SOCKET_MESSAGE_SWITCHORDER_H
#define LIANCHENG_SOCKET_MESSAGE_SWITCHORDER_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace liancheng_socket
{
template <class ContainerAllocator>
struct SwitchOrder_
{
  typedef SwitchOrder_<ContainerAllocator> Type;

  SwitchOrder_()
    : header()
    , station_num(0)
    , switch_num(0)
    , case_num(0)  {
    }
  SwitchOrder_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , station_num(0)
    , switch_num(0)
    , case_num(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _station_num_type;
  _station_num_type station_num;

   typedef uint16_t _switch_num_type;
  _switch_num_type switch_num;

   typedef uint8_t _case_num_type;
  _case_num_type case_num;





  typedef boost::shared_ptr< ::liancheng_socket::SwitchOrder_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::liancheng_socket::SwitchOrder_<ContainerAllocator> const> ConstPtr;

}; // struct SwitchOrder_

typedef ::liancheng_socket::SwitchOrder_<std::allocator<void> > SwitchOrder;

typedef boost::shared_ptr< ::liancheng_socket::SwitchOrder > SwitchOrderPtr;
typedef boost::shared_ptr< ::liancheng_socket::SwitchOrder const> SwitchOrderConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::liancheng_socket::SwitchOrder_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::liancheng_socket::SwitchOrder_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::liancheng_socket::SwitchOrder_<ContainerAllocator1> & lhs, const ::liancheng_socket::SwitchOrder_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.station_num == rhs.station_num &&
    lhs.switch_num == rhs.switch_num &&
    lhs.case_num == rhs.case_num;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::liancheng_socket::SwitchOrder_<ContainerAllocator1> & lhs, const ::liancheng_socket::SwitchOrder_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace liancheng_socket

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::liancheng_socket::SwitchOrder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::liancheng_socket::SwitchOrder_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::liancheng_socket::SwitchOrder_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::liancheng_socket::SwitchOrder_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::liancheng_socket::SwitchOrder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::liancheng_socket::SwitchOrder_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::liancheng_socket::SwitchOrder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6c01d75e528ea11677c0e88f7ad7f7a1";
  }

  static const char* value(const ::liancheng_socket::SwitchOrder_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6c01d75e528ea116ULL;
  static const uint64_t static_value2 = 0x77c0e88f7ad7f7a1ULL;
};

template<class ContainerAllocator>
struct DataType< ::liancheng_socket::SwitchOrder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "liancheng_socket/SwitchOrder";
  }

  static const char* value(const ::liancheng_socket::SwitchOrder_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::liancheng_socket::SwitchOrder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"uint8  station_num\n"
"uint16  switch_num\n"
"uint8  case_num\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::liancheng_socket::SwitchOrder_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::liancheng_socket::SwitchOrder_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.station_num);
      stream.next(m.switch_num);
      stream.next(m.case_num);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SwitchOrder_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::liancheng_socket::SwitchOrder_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::liancheng_socket::SwitchOrder_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "station_num: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.station_num);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "switch_num: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.switch_num);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "case_num: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.case_num);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIANCHENG_SOCKET_MESSAGE_SWITCHORDER_H
