# 请求
uint8 station_num       # 电机站号
string control_type      # 控制类型：'position', 'velocity', 'enable'
int32 position           # 位置目标值
uint16 threshold         # 位置允许误差
int16 velocity           # 速度目标值
uint16 acc               # 加速度
uint16 dec               # 减速度
bool enable              # 使能状态
---
bool success             # 是否成功
string message           # 响应消息 