set(_CATKIN_CURRENT_PACKAGE "servo_wrist")
set(servo_wrist_VERSION "0.0.0")
set(servo_wrist_MAINTAINER "caobo <caobo@todo.todo>")
set(servo_wrist_PACKAGE_FORMAT "2")
set(servo_wrist_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "message_generation")
set(servo_wrist_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(servo_wrist_BUILDTOOL_DEPENDS "catkin")
set(servo_wrist_BUILDTOOL_EXPORT_DEPENDS )
set(servo_wrist_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "message_runtime")
set(servo_wrist_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "message_runtime")
set(servo_wrist_TEST_DEPENDS )
set(servo_wrist_DOC_DEPENDS )
set(servo_wrist_URL_WEBSITE "")
set(servo_wrist_URL_BUGTRACKER "")
set(servo_wrist_URL_REPOSITORY "")
set(servo_wrist_DEPRECATED "")